---
abstract: 'prepend lines at the top of your perl files'
author:
  - 'Jerome Quelin'
build_requires:
  Dist::Zilla::Tester: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Path::Class: 0
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200012, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Prepender
provides:
  Dist::Zilla::Plugin::Prepender:
    file: lib/Dist/Zilla/Plugin/Prepender.pm
    version: 1.112280
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Prepender
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Prepender/
  repository: git://github.com/jquelin/dist-zilla-plugin-prepender.git
  x_MailingList: http://www.listbox.com/subscribe/?list_id=139292
version: 1.112280
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.110930
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@JQUELIN/ReportVersions::Tiny'
      version: 1.03
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: '@JQUELIN/PruneFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@JQUELIN/AutoPrereqs'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.103470
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.12060501
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@JQUELIN/MetaJSON'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git::Check'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git::Commit'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@JQUELIN/Git::CommitBuild'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagMaster'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/TagRelease'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git::Push'
      version: 1.111590
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.200012
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.200012
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.200012
